version: '3'

services:
  nats-1:
    image: nats:2.10-alpine
    command: -js -sd /data -n nats-cluster-1 --cluster_name nats-cluster -cluster nats://0.0.0.0:6222 -routes nats://nats-2:6222,nats://nats-3:6222,nats://nats-4:6222,nats://nats-5:6222 -p 4222 -m 8222
    volumes:
      - "./data/nats-1:/data"
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - nats-network

  nats-2:
    image: nats:2.10-alpine
    command: -js -sd /data  -n nats-cluster-2 --cluster_name nats-cluster -cluster nats://0.0.0.0:6222 -routes nats://nats-1:6222,nats://nats-3:6222,nats://nats-4:6222,nats://nats-5:6222 -p 4222 -m 8222
    volumes:
      - "./data/nats-2:/data"
    networks:
      - nats-network

  nats-3:
    image: nats:2.10-alpine
    command: -js -sd /data  -n nats-cluster-3 --cluster_name nats-cluster -cluster nats://0.0.0.0:6222 -routes nats://nats-1:6222,nats://nats-2:6222,nats://nats-4:6222,nats://nats-5:6222 -p 4222 -m 8222
    volumes:
      - "./data/nats-3:/data"
    networks:
      - nats-network

  nats-4:
    image: nats:2.10-alpine
    command: -js -sd /data  -n nats-cluster-4 --cluster_name nats-cluster -cluster nats://0.0.0.0:6222 -routes nats://nats-1:6222,nats://nats-2:6222,nats://nats-3:6222,nats://nats-5:6222 -p 4222 -m 8222
    volumes:
      - "./data/nats-4:/data"
    networks:
      - nats-network

  nats-5:
    image: nats:2.10-alpine
    command: -js -sd /data  -n nats-cluster-5 --cluster_name nats-cluster -cluster nats://0.0.0.0:6222 -routes nats://nats-1:6222,nats://nats-2:6222,nats://nats-3:6222,nats://nats-4:6222 -p 4222 -m 8222
    volumes:
      - "./data/nats-5:/data"
    networks:
      - nats-network

networks:
  nats-network:
    driver: bridge
