name: Run Test Suite
on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-tests-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install docker-compose
      run: |
        sudo apt install docker-compose

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test
